//       #include "histset2enums.h" 
// bookeeping enumeration: if we do this we don't need to worry about hist pointer copies and merging
       enum th1d_ids{
		id_ptHist,
	 	id_pzHist,
		id_numpcHist,
		id_numpccutHist,
		id_numSPCHist,
		id_ptSPCHist,
                id_numHGNPCHist,
		id_effPtN,
		id_effPtD,
		id_purityPtN,
		id_purityPtD,
		id_effRN,
		id_effRD,
		id_purityRN,
		id_purityRD,
		id_effXPN,
		id_effXPD,
		id_purityXPN,
		id_purityXPD,
		id_trueGeom,
		id_trueGeom_Coarse,
		id_trueConv,
		id_trueConv_Coarse,
		id_nconvPt_match,
		id_nconvR_match,
		id_nconvXP_match,
		id_nconvPt_fake,
		id_nconvR_fake,
		id_nconvXP_fake,
		id_nconvPt_all,
		id_nconvR_all,
		id_nconvXP_all,		
            numTH1Hist};
       
	enum th2d_ids{
		id_xyHist,
		id_xywideHist,
		id_rphiHist, 
            numTH2Hist};
