//       #include "histset2enums.h" 
// bookeeping enumeration: if we do this we don't need to worry about hist pointer copies and merging
       enum th1d_ids{
		id_ptHist,
	 	id_pzHist,
		id_numpcHist,
		id_numpccutHist,
                id_ptCutHist,
		id_pzCutHist,
		id_numSPCHist,
		id_ptSPCHist,
		id_xplusSPCHist,
		id_minTkPtSPCHist,
		id_mindLc0,
		id_mindLb0,
		id_mindLx0,
		id_mindL2x0,
		id_mindLc1,
                id_mindLb1,
                id_mindLx1,
                id_mindL2x1,
		id_comp0,
		id_comp1,
                id_numHGNPCHist,
		id_ptHCutHist,
		id_pzHCutHist,
		id_ptnum1,
		id_ptnumB1,
		id_ptnumU1,
		id_xpnum1,
		id_xpnumB1,
		id_xpnumU1,
		id_minTknum1,
		id_minTknumB1,
		id_minTknumU1,
		id_Rnum1,
		id_RnumB1,
		id_RnumU1,
		id_Rwidenum1,
		id_RwidenumB1,
		id_RwidenumU1,
		id_ptden1,
		id_xpden1,
		id_minTkden1,
		id_Rden1,
		id_Rwideden1,
            numTH1Hist};
       
	enum th2d_ids{
		id_xyHist,
		id_xywideHist,
		id_rphiHist, 
            numTH2Hist};
